//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebProje2.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ILETISIM
    {
        public int ILETISIMID { get; set; }
        public string ADSOYAD { get; set; }
        public string MAIL { get; set; }
        public string TELEFON { get; set; }
        public string SEHIR { get; set; }
        public string MESAJICERIK { get; set; }
    }
}
