//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebProje2.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class BlogDbEntities : DbContext
    {
        public BlogDbEntities()
            : base("name=BlogDbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BLOG> BLOG { get; set; }
        public virtual DbSet<HAKKIMIZDA> HAKKIMIZDA { get; set; }
        public virtual DbSet<ILETISIM> ILETISIM { get; set; }
        public virtual DbSet<KATEGORI> KATEGORI { get; set; }
        public virtual DbSet<TUR> TUR { get; set; }
        public virtual DbSet<YORUM> YORUM { get; set; }
    
        public virtual ObjectResult<YorumGetir_Result> YorumGetir()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<YorumGetir_Result>("YorumGetir");
        }
    }
}
